# Generated by Django 6.0 on 2025-12-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdSolver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
