# Generated by Django 6.0 on 2025-12-22 10:43

from django.db import migrations
from django.db.models import Count


def remove_duplicate_solutions(apps, schema_editor):
    Solution = apps.get_model('CrowdSolver', 'Solution')
    # find groups with more than one solution per (created_by, issue)
    duplicates = Solution.objects.values('created_by_id', 'issue_id').annotate(cnt=Count('id')).filter(cnt__gt=1)
    for d in duplicates:
        sols = Solution.objects.filter(created_by_id=d['created_by_id'], issue_id=d['issue_id']).order_by('id')
        keep = sols.first()
        # delete all but the one we keep
        sols.exclude(id=keep.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdSolver', '0002_solution_is_approved'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_solutions, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together={('created_by', 'issue')},
        ),
    ]
