# Generated by Django 6.0 on 2025-12-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdSolver', '0003_alter_solution_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together=set(),
        ),
    ]
